global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_label_prometheus_scrape_enabled]
        regex: "true"
        action: keep
      - source_labels: [__meta_docker_container_label_prometheus_scrape_port]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /metrics
      - source_labels: [__address__, __meta_docker_container_label_prometheus_scrape_port]
        regex: (.+):(.+)
        target_label: __address__
        replacement: ${1}:${2}
      - source_labels: [__meta_docker_container_name]
        regex: /(.+)
        target_label: container_name